addSbtPlugin("org.typelevel" %% "sbt-catalysts" % "0.42")
addSbtPlugin("de.heikoseeberger" % "sbt-header" % "5.6.0")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest" % "0.9.9")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("com.codecommit" %% "sbt-github-actions" % "0.10.1")
addSbtPlugin("com.47deg" % "sbt-microsites" % "1.3.0")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.2.16")
